.Dd September 3, 2025
.Dt XMDTAROT 6
.Os
.Sh NAME
.Nm xmdtarot
.Nd "X11/Motif Discordian Tarot program"
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility draws your (or someone else's) super-helpful Discordian Tarot reading.
.Pp
The spread is drawn as a pentagon with the positions of True on top, Seek next,\
then False, then Avoid, and, finally, Meaningless. See if you can spot the \
pattern!
.Pp
.Sh KEYS
.Bl -tag -width Ds
.It Ao Ctrl Ac + Aq M
Show putative card meanings below cards. Of course, you're free to add whatever meaning you'd like; all things are true|false|meaningless anyway.
.It Ao Ctrl Ac + Aq N
Draw a new spread (each second seeds the RNG so doing it too often leads to it not actually drawing a new spread)
.It Ao Ctrl Ac + Aq Q
Quit the program
.El
.Sh SEE ALSO
.Xr ddate 1
.Xr dtarot 6
.Sh DISTRIBUTION POLICY
Public domain.
All rites reversed.
.\" fnord
.Sh AUTHORS
.An This program: Lord Imbrius the Despondent Aq Mt darthferrett@gmail.com
.An Original deck design: Max Flax Beeblewax, and
.An (boing!) Cnoocy Mosque O'Witz Aq Mt marc@suberic.net
.Sh AVAILABILITY
The
Source code is available at
.Lk https://github.com/lorimbrius/xmdtarot
